<?php

/**
 * BaseCustomers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $customername
 * 
 * @method string    getCustomername() Returns the current record's "customername" value
 * @method Customers setCustomername() Sets the current record's "customername" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customers');
        $this->hasColumn('customername', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}