<?php

/**
 * CustomersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustomersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Customers');
    }
}