# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: Customers, action: index }

# generic rules
# please, remove them by adding more specific rules
Users:
  url: /:module/:action
  param: { action: action, sf_format:json}
  requirements:
   sf_format: (?:html|json)


default_index:
  url:   /:module/:action
  param: { action: index, sf_format:json}
  requirements:
  sf_format: (?:html|json)


login:
  url:   /:module/login
  param: { action: login}
#  requirements:


default:
  url:   /:module/:action/*
