<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/03 23:06:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=test',
  'username' => 'root',
  'password' => 'test',
  'name' => 'doctrine',
)),);
