<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/04 17:03:43
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
  ),
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
