<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/04 15:58:50
$this->security = array (
  'index' => 'is_secure:false',
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
