<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/03 23:44:27
$this->security = array (
  'index' => 'is_secure:false',
  'login' => 'is_secure:false',
  'all' => 
  array (
    'is_secure' => false,
  ),
);
